-- Module 3 (How Chatbots & LLMs Think) content enrichment: adds visual
-- diagrams, in-lesson practice checks, worked code examples, and (lesson 19)
-- an interactive code_practice. Additive only (jsonb ||), existing hook/
-- explanation/analogy/fun_fact/try_it fields are untouched.
--
-- Lesson 15 simulates real next-token prediction with a tiny bigram model;
-- lesson 16 makes the context-window limit concrete with real token counts;
-- lesson 18 simulates temperature's effect on sampling with real probabilities
-- (verified against Python's actual random.choices output) instead of staying
-- at pure analogy.

UPDATE public.lesson_content lc
SET content = lc.content || '{"code":"# A tiny \"next-word predictor\" — the same core idea behind a real LLM,\n# just far smaller and far dumber\ntraining_text = \"the cat sat on the mat the cat ran\"\nwords = training_text.split()\n\n# Count what word follows each word, across the training text\nfollows = {}\nfor i in range(len(words) - 1):\n    current, nxt = words[i], words[i + 1]\n    follows.setdefault(current, []).append(nxt)\n\nprint(follows[\"the\"])   # every word ever seen right after \"the\"\nprint(follows[\"cat\"])   # every word ever seen right after \"cat\"\n\n# \"Predict\" by picking the most common next word seen in training\nfrom collections import Counter\ndef predict_next(word):\n    options = follows.get(word, [])\n    return Counter(options).most_common(1)[0][0] if options else None\n\nprint(predict_next(\"the\"))   # a real LLM does this with billions of examples","visual":{"caption":"What actually happens between your prompt and the reply","steps":[{"emoji":"📚","label":"Massive Text","caption":"Trained on an enormous amount of human writing."},{"emoji":"🔤","label":"Tokenize","caption":"Your prompt gets chopped into small chunks (tokens)."},{"emoji":"🎲","label":"Predict Next Token","caption":"The model calculates the probability of every possible next token."},{"emoji":"👆","label":"Sample One","caption":"It picks one token, weighted by those probabilities."},{"emoji":"🔁","label":"Append & Repeat","caption":"That token joins the text, and the whole process runs again."}]},"practice":{"prompt":"\"Large\" in Large Language Model mainly refers to what?","options":["The amount of training text AND the number of adjustable internal parameters","The physical size of the computer it runs on","How long each individual response is","The number of programming languages it was written in"],"correct_index":0,"feedback":"Modern LLMs have billions of parameters — the internal numbers that store what the model learned — trained on enormous amounts of text."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 15;

UPDATE public.lesson_content lc
SET content = lc.content || '{"code":"# LLMs don''t read whole words — they read \"tokens\", small chunks of text.\n# Real tokenizers are trained on huge text corpora, but here''s the idea:\ntext = \"unbelievable\"\n\nword_level    = [text]                      # naive: one token per word\nsubword_level = [\"un\", \"believ\", \"able\"]    # closer to how a real tokenizer splits it\n\nprint(f\"Word-level: {len(word_level)} token(s)\")\nprint(f\"Subword-level: {len(subword_level)} token(s)\")\n\n# A context window is just a LIMIT on how many tokens fit in one request\ncontext_window = 8\nprompt_tokens = [\"Explain\", \"photo\", \"synthesis\", \"in\", \"one\", \"sentence\", \"please\", \"now\", \"quickly\"]\nfits = len(prompt_tokens) <= context_window\nprint(f\"Prompt has {len(prompt_tokens)} tokens, window holds {context_window} -> fits: {fits}\")","visual":{"caption":"Why \"the model forgot what I said earlier\" happens","steps":[{"emoji":"✂️","label":"Split Into Tokens","caption":"Every message, yours and the model''s, gets tokenized."},{"emoji":"📏","label":"Count Against the Window","caption":"The whole conversation has a fixed token limit — the context window."},{"emoji":"✅","label":"Fits","caption":"Everything''s visible to the model at once."},{"emoji":"✂️","label":"Truncated","caption":"Over the limit, and the oldest tokens get dropped from view."}]},"practice":{"prompt":"A conversation grows past the model''s context window. What actually happens?","options":["The oldest messages fall out of view — the model literally can no longer see them","The model automatically remembers everything forever, with no limit","The app crashes and loses all data","Tokens have no real limit, so this never happens"],"correct_index":0,"feedback":"The context window is a hard limit on how many tokens the model can attend to at once — once it is full, the oldest content is pushed out of view."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 16;

UPDATE public.lesson_content lc
SET content = lc.content || '{"code":"def build_prompt(system_message, user_message):\n    return f\"[SYSTEM]: {system_message}\\n[USER]: {user_message}\"\n\nformal_bot  = \"You are a formal, professional assistant. Always use complete sentences.\"\nplayful_bot = \"You are a playful, funny assistant. Use emojis and jokes.\"\n\nuser_question = \"What''s the weather like today?\"\n\nprint(build_prompt(formal_bot, user_question))\nprint()\nprint(build_prompt(playful_bot, user_question))","visual":{"caption":"How a system prompt turns a blank model into a character","steps":[{"emoji":"⬜","label":"No System Prompt","caption":"Generic tone, no consistent personality."},{"emoji":"🎭","label":"+ Personality","caption":"A tone and voice — formal, playful, sarcastic, calm."},{"emoji":"🚧","label":"+ Rules & Boundaries","caption":"Topics it won''t touch, things it always/never does."},{"emoji":"📖","label":"+ Knowledge","caption":"Facts specific to your use case that it should treat as true."},{"emoji":"🤖","label":"A Real Character","caption":"Consistent, on-brand, and predictable across every reply."}]},"practice":{"prompt":"A system prompt says \"You are an expert in 14th-century French history.\" Does this actually make the model an expert?","options":["No — it shapes tone and framing, but does not add real knowledge the model was never trained on","Yes — the model instantly gains a real history degree","It makes the model refuse all other questions forever","System prompts have zero effect on the model''s behavior"],"correct_index":0,"feedback":"A system prompt shapes HOW the model responds — tone, focus, persona — it can''t grant knowledge the model was never trained on. That''s why lesson 28 covers actually teaching your bot real facts separately."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 17;

UPDATE public.lesson_content lc
SET content = lc.content || '{"code":"import random\n\n# A tiny simulation of how temperature affects word choice.\n# Higher temperature \"flattens\" the odds, making rarer picks more likely.\nword_probs = {\"happy\": 0.6, \"content\": 0.25, \"ecstatic\": 0.1, \"furious\": 0.05}\n\ndef pick_with_temperature(probs, temperature):\n    words = list(probs.keys())\n    weights = [p ** (1 / temperature) for p in probs.values()]\n    return random.choices(words, weights=weights, k=1)[0]\n\nrandom.seed(1)\nprint(\"Low temperature (0.3):\", [pick_with_temperature(word_probs, 0.3) for _ in range(6)])\nrandom.seed(1)\nprint(\"High temperature (1.5):\", [pick_with_temperature(word_probs, 1.5) for _ in range(6)])","visual":{"caption":"Same model, same prompt, different randomness","steps":[{"emoji":"🧊","label":"Low Temperature","caption":"Predictable, repetitive, \"safe\" — sticks to the most likely words."},{"emoji":"🌤️","label":"Medium Temperature","caption":"A balance of consistency and variety."},{"emoji":"🔥","label":"High Temperature","caption":"Creative and varied — but sometimes incoherent or odd."}]},"practice":{"prompt":"Which temperature setting fits a customer-support bot that must give consistent, predictable answers?","options":["Low temperature","High temperature","Temperature has no effect on consistency","It should be set randomly each time"],"correct_index":0,"feedback":"Low temperature keeps the model close to its single most likely answer every time — exactly what you want when consistency matters more than creativity."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 18;

UPDATE public.lesson_content lc
SET content = lc.content || '{"code":"vague_prompt = \"Tell me about dogs\"\n\ngood_prompt = \"\"\"You are a veterinarian assistant.\nTask: Explain the three most important things a first-time dog owner\nshould know about feeding a puppy.\nFormat: A numbered list, each point one sentence, no more than 60 words total.\n\"\"\"\n\nprint(\"VAGUE PROMPT gives the model: no role, no specific task, no format\")\nprint(\"GOOD PROMPT gives the model: a role, a specific task, and an exact format\")\nprint(f\"\\nGood prompt length: {len(good_prompt.split())} words\")","visual":{"caption":"The five ingredients of a prompt that actually works","steps":[{"emoji":"🎭","label":"Role","caption":"Who should the model act as?"},{"emoji":"🎯","label":"Task","caption":"The exact thing you want done, stated plainly."},{"emoji":"📋","label":"Context","caption":"Any background facts the model needs to know."},{"emoji":"📐","label":"Format","caption":"Exactly how the answer should be structured."},{"emoji":"🚧","label":"Constraints","caption":"Length limits, things to avoid, tone requirements."}]},"practice":{"prompt":"What is the biggest problem with the prompt \"Tell me about dogs\"?","options":["It gives no task, format, or constraints, so the response length and focus are unpredictable","It is too long and detailed","It uses the word \"dogs\" instead of \"canines\"","Nothing — vague prompts always produce the best answers"],"correct_index":0,"feedback":"Without a role, specific task, or format, the model has to guess what you actually want — which is exactly why the same vague prompt can give wildly different answers each time."},"code_practice":{"instructions":"This system prompt has a role and a rule, but never tells the model HOW to format its answer. Add one line specifying a format — for example, mention a numbered list, a single sentence, bullet points, or a short paragraph.","starter":"system_prompt = \"\"\"You are a helpful assistant that explains AI concepts\nto beginners. Keep answers short.\n\"\"\"\n\n# TODO: add ONE more line inside the triple-quoted string above that tells\n# the model exactly HOW to structure its response.\n\nprint(system_prompt)","check_pattern":"(numbered list|bullet point|one sentence|short paragraph|step[- ]by[- ]step|\\bformat\\b)","success_message":"Now the model knows not just WHAT to say, but exactly HOW to structure it — the difference between a usable answer and a guessing game.","hint":"Try adding a line like: \"Respond in a numbered list.\" or \"Answer in exactly one sentence.\""}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 19;

