-- Module 6 (Responsible & Ethical AI): the final module. Publishes full
-- content + quizzes for all 4 remaining stubs, completing the full 34-lesson
-- curriculum (6+8+5+6+5+4). No expansion flagged for this module.

INSERT INTO public.lesson_content (lesson_id, content)
SELECT id, '{
  "hook": "You got a preview of AI bias back in Module 2''s ''When AI Gets It Wrong.'' Now let''s go deeper: where bias actually comes from, why it''s genuinely hard to fully eliminate, and what you can realistically do about it as a builder.",
  "explanation": "Bias in AI means a model''s outputs systematically favor or disadvantage certain groups, usually unintentionally, almost always traceable to training data or design choices. Several distinct sources: Historical bias — training data reflects past biased human decisions, and the model faithfully learns and repeats that pattern. Representation bias — certain groups are underrepresented in training data, so the model has less signal to learn from about them, performing worse by default, not out of malice. Measurement bias — the way data was labeled or collected itself encodes bias, like inconsistent labeling standards across groups. Aggregation bias — a single model trained on everyone might work well ''on average'' while performing badly for specific subgroups whose needs genuinely differ. Fully eliminating bias is genuinely difficult — real-world data is never perfectly balanced. But you can meaningfully reduce it: check whether your training/example data represents the full range of actual users, test across different groups and phrasings rather than one ''default'' tester, and stay skeptical of AI output involving judgments about people rather than trusting it uncritically.",
  "analogy": "Bias in AI is like a photocopier calibrated using only bright white paper — it copies white paper perfectly, but every other color comes out systematically distorted, not out of malice, but because it was only ever calibrated against one narrow case.",
  "fun_fact": "One famous documented case: early facial recognition systems performed dramatically worse on darker-skinned faces and women than on lighter-skinned men, largely because benchmark datasets were overwhelmingly composed of lighter-skinned male faces — a gap that led to real changes in how the field builds and evaluates these systems.",
  "try_it": "Think about who tested your FORGE bot so far — probably just you and a few similar friends. List one type of user who might interact with your bot very differently than your existing testers did."
}'::jsonb
FROM public.lessons WHERE slug = 'bias-in-ai';

INSERT INTO public.lesson_content (lesson_id, content)
SELECT id, '{
  "hook": "Building an AI bot means people might tell it things they wouldn''t tell a stranger — worries, personal details, sometimes things they''re struggling with. That trust comes with real responsibility.",
  "explanation": "Privacy and safety cover several distinct concerns. Data privacy: what happens to information a user shares — is it stored, where, for how long, who can access it? Even in a learning project, it''s worth genuinely thinking through, not just shipping and forgetting. Sensitive topic handling: some subjects (mental health, medical symptoms, safety concerns) deserve careful handling — BLOCKED_TOPICS and RULES from Module 4 exist partly for this, and a well-built bot should know when to gently redirect toward a real trusted adult or professional resource. Manipulation resistance: can a user talk your bot into ignoring its own safety rules through clever phrasing or persistent pressure? This is a real, actively studied problem called ''jailbreaking,'' and no system is perfectly immune — which is why defense-in-depth (multiple overlapping safety layers) matters more than any single safeguard. Age-appropriateness: a bot''s tone and boundaries should genuinely match its actual intended audience. None of this means building overly restrictive, joyless bots — it means considering not just ''can my bot do this'' but ''should it, and what happens if someone misuses it.''",
  "analogy": "Building safety into a bot is like designing a playground, not posting a single ''be careful'' sign. You think about fall height, materials, spacing, and age-appropriate equipment together, because kids will genuinely test limits, sometimes in ways you didn''t predict, and good design assumes that.",
  "fun_fact": "Deliberately trying to get an AI system to break its own safety rules — ''jailbreaking'' or ''red teaming'' — has become such an established discipline that major AI companies run structured bug-bounty-style programs paying skilled people to find weaknesses before malicious users do.",
  "try_it": "Think of one sensitive topic your bot might realistically encounter. Check: does your BLOCKED_TOPICS or RULES currently handle it thoughtfully, or would your bot just wing it?"
}'::jsonb
FROM public.lessons WHERE slug = 'privacy-safety-guardrails';

INSERT INTO public.lesson_content (lesson_id, content)
SELECT id, '{
  "hook": "AI isn''t just a technical tool sitting quietly on a server — it''s already reshaping jobs, creativity, information, and daily life at a scale most people haven''t fully processed yet.",
  "explanation": "A few actively debated dimensions of AI''s real-world impact. Jobs and work: AI automates specific tasks within jobs more often than entire jobs outright, creating real disruption for some while creating new roles (the AI careers from Module 1) for others — researchers genuinely disagree about the net long-term effect. Creativity and authorship: AI-generated art, music, and writing raise real, unresolved questions about originality, credit, and fair compensation for the human artists whose work trained the models — actively contested in courts and legislatures worldwide. Misinformation: the same generative capabilities that build a fun chatbot also make convincing fake text, images, audio, and video (''deepfakes'') easier to create at scale — a genuine challenge for trust in what people see online. Access and equity: AI tools and benefits aren''t distributed evenly — access tends to concentrate among people/regions who already had more resources, potentially widening existing gaps unless deliberately addressed. None of this means AI is simply ''bad'' — it means understanding real tradeoffs honestly, rather than uncritical hype or blanket fear, is the mindset of a responsible builder.",
  "analogy": "AI''s societal impact is like the arrival of the internet or the automobile in their own eras — genuinely transformative, creating real new opportunities and real new problems simultaneously, playing out over years and decades rather than resolving overnight.",
  "fun_fact": "Surveys of AI researchers themselves consistently show real disagreement about AI''s long-term societal impact, ranging from strong optimism to serious concern, even among genuine experts — a strong signal these are honestly open, contested questions, not settled science.",
  "try_it": "Pick one of the four impact areas from this lesson. Write one sentence about how it could show up specifically in something you personally care about."
}'::jsonb
FROM public.lessons WHERE slug = 'ai-impact-on-society';

INSERT INTO public.lesson_content (lesson_id, content)
SELECT id, '{
  "hook": "You made it through all the lessons — from ''what even is AI'' to building real chatbots and agents to thinking seriously about ethics. This last one isn''t new material — it''s about turning everything you''ve learned into an actual next step.",
  "explanation": "Let''s connect the dots. Module 1 covered what AI actually is versus the sci-fi version, and the range of careers in this field. Module 2 built real intuition for how machine learning works: data, training, classification/regression, and honest model evaluation. Module 3 opened up exactly how chatbots function under the hood — tokens, context windows, system prompts, temperature, prompt engineering. Module 4 turned all of that into hands-on practice, building a real bot''s identity, knowledge, tone, and safety boundaries, then testing it rigorously. Module 5 pushed into agents — tool use, visible reasoning, multi-step planning, and how memory actually works inside an LLM. And this module grounded all of it in responsibility: bias, privacy, safety, and AI''s real, still-unfolding impact on the world. The honest truth: this course gave you a genuinely solid foundation, but the field moves fast, and the real skill going forward is knowing how to keep learning deliberately — building more ambitious FORGE projects, researching a specific AI career path from Module 1, following the field with the same critical mindset Module 6 asked for, and actually showing what you built to someone else, since teaching cements understanding better than almost anything else.",
  "analogy": "Finishing this course is like finishing driver''s ed, not retiring from driving. You''ve learned the real rules, mechanics, and hazards to watch for — but the actual skill and judgment build through the driving you do next, on real roads, in situations no course could fully predict.",
  "fun_fact": "Many working AI professionals describe their day-to-day learning as an ongoing habit, not a one-time achievement: reading new papers, testing new tools, and rebuilding their mental models regularly, because the field changes fast enough that standing still for even a year means falling meaningfully behind.",
  "try_it": "Write down one concrete, specific next action — not a vague goal like ''learn more AI,'' but something real and scheduled: a specific new FORGE project idea, a specific career path to research this week, or a specific person you want to show your best bot to. Then actually go do it."
}'::jsonb
FROM public.lessons WHERE slug = 'your-path-forward';

UPDATE public.lessons SET is_published = true WHERE slug IN ('bias-in-ai', 'privacy-safety-guardrails', 'ai-impact-on-society', 'your-path-forward');

INSERT INTO public.lesson_quiz_questions (lesson_id, order_index, question, options, correct_index, explanation)
SELECT id, q.order_index, q.question, q.options::jsonb, q.correct_index, q.explanation
FROM public.lessons, LATERAL (
  VALUES
    (1, 'What does "bias" in AI generally refer to?', '["A model that runs slowly", "Outputs that systematically favor or disadvantage certain groups, usually unintentionally", "A model with too many parameters", "A deliberate, always-intentional design choice"]', 1, 'AI bias refers to systematic, usually unintentional favoring/disadvantaging of certain groups.'),
    (2, 'What is "historical bias"?', '["Bias that only affects old computers", "Training data reflecting past biased human decisions, which the model then repeats", "A bias only found in history textbooks", "A bug unrelated to data"]', 1, 'Historical bias occurs when a model repeats biased patterns already present in past data.'),
    (3, 'What is "representation bias"?', '["A model performing better with extra hardware", "Certain groups being underrepresented in training data, causing worse performance for them by default", "A bias only found in image recognition", "A fictional concept with no real examples"]', 1, 'Underrepresentation in training data leads to weaker model performance for those groups.'),
    (4, 'Can bias in AI be fully, permanently eliminated, per this lesson?', '["Yes, trivially, with one simple setting", "It''s genuinely difficult, since real-world data is rarely perfectly balanced, but it can be meaningfully reduced", "Bias is not a real issue", "Only unsupervised models can have bias"]', 1, 'Full elimination is hard, but deliberate practices can meaningfully reduce bias.'),
    (5, 'What practical step does this lesson recommend for reducing bias in your own bots?', '["Never test with more than one person", "Check whether your data represents the full range of actual users, and test across different groups/phrasings", "Bias reduction requires no testing", "Only test with people who think exactly like you"]', 1, 'Deliberately testing across diverse users and phrasings helps catch bias.'),
    (6, 'In the photocopier analogy, what does calibrating only on white paper represent?', '["A perfectly unbiased, fully general system", "A system tuned on a narrow case that then performs poorly outside it", "A malicious, deliberately biased design", "An error unrelated to training data"]', 1, 'Narrow calibration mirrors how training on unrepresentative data leads to poor generalization.'),
    (7, 'What real example did this lesson mention regarding facial recognition bias?', '["Facial recognition has never shown any bias", "Early systems performed worse on darker-skinned faces and women due to unrepresentative datasets", "This example is purely hypothetical", "Facial recognition bias only affects fictional characters"]', 1, 'This is a well-documented real case that led to changes in the field.')
) AS q(order_index, question, options, correct_index, explanation)
WHERE lessons.slug = 'bias-in-ai';

INSERT INTO public.lesson_quiz_questions (lesson_id, order_index, question, options, correct_index, explanation)
SELECT id, q.order_index, q.question, q.options::jsonb, q.correct_index, q.explanation
FROM public.lessons, LATERAL (
  VALUES
    (1, 'What does "data privacy" concern in AI bots?', '["How fast the bot responds", "What happens to information a user shares — where it''s stored, for how long, who can access it", "The bot''s temperature setting", "The bot''s visual color scheme"]', 1, 'Data privacy concerns the handling, storage, and access of user-shared information.'),
    (2, 'What is "jailbreaking" in AI safety?', '["A physical security measure for hardware", "Attempting to manipulate an AI into ignoring its own safety rules through clever phrasing or pressure", "A type of neural network layer", "A feature that speeds up training"]', 1, 'Jailbreaking refers to attempts to bypass an AI system''s built-in safety restrictions.'),
    (3, 'Why does this lesson recommend "defense-in-depth"?', '["A single safeguard is always perfectly sufficient", "No system is perfectly immune to manipulation, so multiple layers provide stronger protection", "Multiple layers always slow the bot with no benefit", "It''s unrelated to AI safety"]', 1, 'Since no single safeguard is foolproof, layering multiple protections is more robust.'),
    (4, 'What should a well-built bot do when it encounters a sensitive topic outside its scope?', '["Attempt to fully handle it regardless of appropriateness", "Gently redirect the user toward a real trusted adult or professional resource", "Ignore the message entirely with no response", "Always give detailed medical or legal advice"]', 1, 'Redirecting toward real-world resources is recommended for topics outside a bot''s scope.'),
    (5, 'What does "age-appropriateness" mean in this context?', '["Only adults are allowed to build bots", "A bot''s tone, content, and boundaries should genuinely match its actual intended audience", "Age has no relevance to bot design", "Only children can use chatbots"]', 1, 'Age-appropriateness means designing around the bot''s real intended users.'),
    (6, 'In the playground analogy, what does "one be careful sign" represent?', '["A thorough, well-layered safety design", "An insufficient, single-safeguard approach to safety", "The ideal approach to bot safety", "A concept unrelated to AI"]', 1, 'A single sign mirrors relying on just one safeguard instead of layered design.'),
    (7, 'What have major AI companies established to find safety weaknesses proactively?', '["Nothing, this practice doesn''t exist", "Structured bug-bounty-style programs paying people to find weaknesses", "A ban on all safety testing", "Only internal employees may ever test safety"]', 1, 'Bug-bounty-style red teaming is a real, established practice.')
) AS q(order_index, question, options, correct_index, explanation)
WHERE lessons.slug = 'privacy-safety-guardrails';

INSERT INTO public.lesson_quiz_questions (lesson_id, order_index, question, options, correct_index, explanation)
SELECT id, q.order_index, q.question, q.options::jsonb, q.correct_index, q.explanation
FROM public.lessons, LATERAL (
  VALUES
    (1, 'Is AI''s economic effect on jobs a fully settled, agreed-upon question, per this lesson?', '["Yes, universal agreement exists", "No — it''s an honest, actively debated open question", "AI has no effect on jobs whatsoever", "Only negative effects have ever been documented"]', 1, 'This lesson describes genuine disagreement among researchers about the net long-term effect.'),
    (2, 'What unresolved question does AI-generated creative content raise?', '["Whether computers can display images at all", "Questions about originality, credit, and fair compensation for human artists", "Whether AI-generated content is technically possible", "This is a fully solved, non-controversial issue"]', 1, 'Authorship, credit, and compensation are actively contested, unresolved issues.'),
    (3, 'What is a "deepfake"?', '["A type of neural network layer", "Convincing fake text, image, audio, or video content created using generative AI", "A term for a very deep ocean", "A category of supervised learning task"]', 1, 'Deepfakes are realistic synthetic media created using generative AI.'),
    (4, 'What does this lesson mean by AI''s benefits not being distributed evenly?', '["Everyone has exactly equal access to AI tools and skills", "Access tends to concentrate among people/regions with more existing resources", "AI access is randomly distributed with no pattern", "This is not a real concern"]', 1, 'Unequal access can widen existing resource gaps rather than close them.'),
    (5, 'What mindset does this lesson recommend for a responsible AI builder?', '["Uncritical hype with no consideration of downsides", "Blanket fear and avoidance of AI entirely", "Honestly understanding the real tradeoffs, rather than either extreme", "Ignoring societal impact entirely"]', 2, 'The lesson recommends honest engagement with both benefits and real risks.'),
    (6, 'In the internet/automobile analogy, what point is made about AI''s impact?', '["AI has no historical parallel whatsoever", "Like past transformative technologies, it creates real new opportunities and problems simultaneously, over years", "AI''s impact resolves completely within a single day", "This analogy suggests AI has no real impact"]', 1, 'Transformative technologies bring mixed, long-unfolding effects, not simple outcomes.'),
    (7, 'What do surveys of AI researchers show about AI''s long-term societal impact?', '["Universal, unanimous agreement", "Real disagreement ranging from optimism to serious concern, even among experts", "No researcher has ever studied this", "Complete indifference from researchers"]', 1, 'Genuine disagreement among experts signals these are honestly open questions.')
) AS q(order_index, question, options, correct_index, explanation)
WHERE lessons.slug = 'ai-impact-on-society';

INSERT INTO public.lesson_quiz_questions (lesson_id, order_index, question, options, correct_index, explanation)
SELECT id, q.order_index, q.question, q.options::jsonb, q.correct_index, q.explanation
FROM public.lessons, LATERAL (
  VALUES
    (1, 'Is memorizing everything from this course the most important skill going forward?', '["Yes, memorization is the entire goal", "No — the real skill is knowing how to keep learning deliberately, since the field moves fast", "Nothing learned in this course matters going forward", "Only Module 4''s content matters"]', 1, 'The lesson emphasizes ongoing, deliberate learning over static memorization.'),
    (2, 'What module covered how machine learning actually works, including honest model evaluation?', '["Module 1", "Module 2", "Module 4", "Module 6"]', 1, 'Module 2 (Machine Learning Fundamentals) covered these core concepts.'),
    (3, 'What is one concrete next step this lesson suggests?', '["Stop building anything related to AI immediately", "Picking an AI career path from Module 1 and researching what it actually requires", "Forgetting everything learned in this course", "Avoiding any further learning about AI"]', 1, 'Researching a specific career path is one concrete suggested next step.'),
    (4, 'Why does this lesson recommend showing someone else what you built?', '["It has no real benefit", "It''s one of the most reliable ways to cement your own understanding", "Teaching others is illegal without certification", "Only professional teachers should explain AI concepts"]', 1, 'Explaining what you''ve built to someone else deepens your own understanding.'),
    (5, 'In the driver''s ed analogy, what does "skill builds through the driving you do next" represent?', '["Finishing this course means you''re completely done learning forever", "Real skill and judgment continue developing through ongoing practice after the course", "Driving and learning AI are entirely unrelated", "No further growth is possible"]', 1, 'Like driving skill after driver''s ed, real AI skill develops through ongoing practice.'),
    (6, 'How do many working AI professionals describe their ongoing learning?', '["As a one-time achievement completed early in their career", "As an ongoing habit of reading, testing, and updating their mental models regularly", "They claim no further learning is necessary", "AI professionals never need to learn anything new"]', 1, 'Continuous learning is often described as a necessary ongoing habit.'),
    (7, 'What kind of "next action" does this lesson recommend writing down?', '["A vague goal like ''learn more AI'' with no specifics", "A concrete, specific, scheduled action like a project idea or a person to show your work to", "No action is necessary after finishing the course", "Only career-related actions count"]', 1, 'The lesson recommends concrete, actionable next steps over vague intentions.')
) AS q(order_index, question, options, correct_index, explanation)
WHERE lessons.slug = 'your-path-forward';
