-- Module 1 (AI Foundations) content enrichment: adds visual diagrams, in-lesson
-- practice checks, and one illustrative code block. Additive only (jsonb ||),
-- existing hook/explanation/analogy/fun_fact/try_it fields are untouched.
-- Also fixes lesson 35's title (UTF-8/Latin-1 mojibake on the arrow character —
-- should read 'Thought → Action → Observation').

UPDATE public.lesson_content lc
SET content = lc.content || '{"visual":{"caption":"From simple rules to real intelligence — narrow AI is a spectrum","steps":[{"emoji":"📏","label":"Rule-Based Systems","caption":"Explicit if-this-then-that logic a programmer writes by hand."},{"emoji":"📊","label":"Machine Learning","caption":"The computer learns patterns from examples instead of hard-coded rules."},{"emoji":"🤖","label":"Narrow AI (Today)","caption":"Very good at ONE specific job — recommending songs, recognizing faces."},{"emoji":"🧠","label":"AGI (Not Real Yet)","caption":"Human-level general intelligence across ANY task — still science fiction."}]},"practice":{"prompt":"Which of these actually exists today?","options":["A chatbot that''s a genuine expert at only ONE thing, like customer support","A robot with real feelings and self-awareness","An AI that can learn literally any human skill instantly","A computer that thinks exactly like a human brain"],"correct_index":0,"feedback":"That''s narrow AI — extremely good at a specific task, with zero real understanding outside it. Everything else on this list is AGI, which doesn''t exist yet."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 1;

UPDATE public.lesson_content lc
SET content = lc.content || '{"visual":{"caption":"The learning loop every ML model runs, over and over","steps":[{"emoji":"📚","label":"Show Examples","caption":"Thousands of labeled examples — ''this is a cat'', ''this is not a cat''."},{"emoji":"🔍","label":"Find Patterns","caption":"The model searches for patterns that separate the categories."},{"emoji":"🎯","label":"Test Itself","caption":"It guesses on examples it hasn''t memorized, and checks if it''s right."},{"emoji":"🔧","label":"Adjust","caption":"Wrong guesses nudge its internal numbers slightly."},{"emoji":"🔁","label":"Repeat","caption":"Thousands of times, until the guesses get consistently better."}]},"practice":{"prompt":"A model trained only on photos of cats taken in daylight is shown a cat photo taken at night. What''s most likely?","options":["It performs worse, because night photos are outside what it learned from","It performs exactly the same, since a cat is a cat","It automatically re-trains itself on the new lighting","It refuses to make a guess"],"correct_index":0,"feedback":"Models only get good at what is actually in their training examples — this is why real datasets need variety, not just volume."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 2;

UPDATE public.lesson_content lc
SET content = lc.content || '{"visual":{"caption":"AI''s rough timeline — decades of hype, ''winters'', and real breakthroughs","steps":[{"emoji":"📏","label":"1950s-60s: Rule-Based AI","caption":"Programmers hand-wrote logic for every situation."},{"emoji":"🧊","label":"1970s-80s: AI Winters","caption":"Funding dried up when rule-based systems hit their limits."},{"emoji":"📈","label":"1990s-2000s: Statistical ML","caption":"Learning from data starts beating hand-written rules."},{"emoji":"🚀","label":"2010s: Deep Learning Boom","caption":"More data plus more compute made neural networks genuinely powerful."},{"emoji":"💬","label":"2020s: The LLM Era","caption":"ChatGPT and friends make AI a daily tool for billions of people."}]},"practice":{"prompt":"Why did early rule-based AI eventually hit a wall?","options":["A programmer can never write enough explicit rules to cover the real world''s messiness","Computers in the 1960s couldn''t run any software at all","Rule-based systems were too fast and needed slowing down","The internet didn''t exist yet, so there were no rules to write"],"correct_index":0,"feedback":"Real-world situations have too many edge cases for anyone to hand-write rules for all of them — machine learning exists precisely to sidestep that problem."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 3;

UPDATE public.lesson_content lc
SET content = lc.content || '{"code":"def neuron(inputs, weights, bias):\n    # Multiply each input by its weight, add them up, add the bias\n    total = sum(i * w for i, w in zip(inputs, weights)) + bias\n    # A simple ''step'' activation: fire (1) if the total clears zero\n    return 1 if total > 0 else 0\n\n# A tiny neuron deciding: should I bring an umbrella?\n# inputs = [chance_of_rain, wind_speed], both 0.0-1.0\ninputs  = [0.9, 0.2]\nweights = [1.0, 0.3]\nbias = -0.5\n\nprint(neuron(inputs, weights, bias))  # 1 = yes, bring it","visual":{"caption":"One neuron, step by step","steps":[{"emoji":"📥","label":"Inputs","caption":"Numbers coming in — e.g. chance of rain, wind speed."},{"emoji":"⚖️","label":"Weights","caption":"Each input gets multiplied by how much it matters."},{"emoji":"➕","label":"Sum + Bias","caption":"Everything gets added up, plus one extra adjustable number."},{"emoji":"⚡","label":"Activation","caption":"A rule decides whether the total is enough to ''fire''."},{"emoji":"📤","label":"Output","caption":"A single number passed on — to a decision, or the next neuron."}]},"practice":{"prompt":"In the umbrella neuron above, what happens if you increase the weight on chance_of_rain?","options":["Rain chance matters MORE to the final decision","Rain chance matters LESS to the final decision","Nothing changes — weights are just decoration","The neuron stops working entirely"],"correct_index":0,"feedback":"Weights control how much each input matters — a bigger weight means that input pushes the total (and the decision) harder."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 4;

UPDATE public.lesson_content lc
SET content = lc.content || '{"visual":{"caption":"AI you probably used today without noticing","steps":[{"emoji":"🔓","label":"Face Unlock","caption":"A model matches your face against a stored pattern in milliseconds."},{"emoji":"🎵","label":"Recommendations","caption":"Predicts what you will like next from what you (and similar people) watched or played."},{"emoji":"📧","label":"Spam Filters","caption":"Classifies every incoming email as spam or not before you even see it."},{"emoji":"🗺️","label":"Traffic Prediction","caption":"Forecasts congestion using live and historical location data."},{"emoji":"🎤","label":"Voice Assistants","caption":"Converts your speech to text, then figures out what you actually want."}]},"practice":{"prompt":"Your maps app reroutes you because it predicts traffic ahead. What kind of AI task is that?","options":["A prediction problem — estimating something that has not happened yet from patterns in data","A classification problem, since there are only two roads to choose from","Not AI at all, just a fixed timer","Random guessing that happens to look smart"],"correct_index":0,"feedback":"Predicting future traffic from live and historical data is a textbook prediction task — the same core idea behind predicting prices, weather, or demand."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 5;

UPDATE public.lesson_content lc
SET content = lc.content || '{"visual":{"caption":"A few of the jobs inside the AI field","steps":[{"emoji":"📊","label":"Data Scientist","caption":"Finds patterns and insights hidden inside messy, real-world data."},{"emoji":"🛠️","label":"ML Engineer","caption":"Builds and deploys the systems that train and run models at scale."},{"emoji":"⚖️","label":"AI Ethicist","caption":"Checks whether an AI system is fair, safe, and honest before it ships."},{"emoji":"✍️","label":"Prompt Engineer","caption":"Designs and tests the instructions that get the best results from an LLM."},{"emoji":"📱","label":"AI Product Manager","caption":"Decides what an AI product should actually do — and for whom."}]},"practice":{"prompt":"A company wants to check whether their hiring AI unfairly rejects certain groups of applicants before launch. Who is most directly responsible for that?","options":["An AI Ethicist","A Prompt Engineer","A Data Scientist alone, with no one else involved","No one — that is not a real job function"],"correct_index":0,"feedback":"Auditing a system for fairness before it affects real people is exactly what an AI Ethicist (often working alongside data scientists) is there to catch."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.order_index = 6;

UPDATE public.lessons SET title = 'Thought → Action → Observation' WHERE order_index = 35;
