-- Module 5 (AI Agents & Tools): publishes full content + quizzes for all 5
-- existing stubs, tied to FORGE's real agent features (tool calling via
-- web_search/calculator/wikipedia, SHOW_REASONING''s ReAct format,
-- REMEMBER_NAME). No expansion flagged for this module.

INSERT INTO public.lesson_content (lesson_id, content)
SELECT id, '{
  "hook": "You''ve built chatbots in FORGE. But ''Agent'' is a different template entirely — not just a chatbot with a fancier name. Here''s exactly what changes.",
  "explanation": "A chatbot reads your message and generates a text response, drawing on SYSTEM_MESSAGE, KNOWLEDGE_BASE, and QA_PAIRS. It can talk ABOUT the world, but can''t actually DO anything in it — check today''s real weather, calculate something new, or look up a fact that changed after training. An agent adds a crucial capability: using tools — real external functions the model can call mid-conversation to get real, current, verifiable information, then incorporate the result. In FORGE, an agent can trigger an actual web search, calculation, or Wikipedia lookup, not just generate text that sounds correct. A plain chatbot asked a math problem or obscure fact is essentially guessing from training patterns (often right, but sometimes confidently wrong — ''hallucination''). An agent with tool access can go get the real answer instead. The tradeoff: agents are more complex to build well, take slightly longer to respond, and need careful instructions about WHEN to use a tool versus answering directly.",
  "analogy": "A chatbot is like a very well-read friend answering purely from memory — impressively knowledgeable, but occasionally wrong about details or unaware of anything recent. An agent is that same friend, except now with a phone in hand — able to pause and actually look something up or do real math, before answering, instead of relying purely on memory.",
  "fun_fact": "The word ''agent'' in AI comes from a much older computer science/philosophy concept: anything that perceives its environment and takes actions to achieve a goal — broad enough to include a thermostat, a chess program, and a modern tool-using AI.",
  "try_it": "Think of a question you''d trust a plain chatbot to answer from memory, and a different question you''d genuinely want it to verify with a real tool (today''s exact date, a live fact). That instinct is exactly the judgment agent-building requires."
}'::jsonb
FROM public.lessons WHERE slug = 'chatbot-vs-agent';

INSERT INTO public.lesson_content (lesson_id, content)
SELECT id, '{
  "hook": "An agent without tools is just a chatbot with extra steps. Let''s look at exactly how FORGE hooks real tools up to your bot, and how the model decides when to actually use one.",
  "explanation": "In FORGE, agent tools work through a routing process behind the scenes, mid-conversation. When your agent receives a message, before generating its main response, a quick internal step examines the message and available tools (web_search, calculator, wikipedia) and decides: does this actually require external information, or can the model answer confidently from what it already knows? If needed, FORGE calls the real tool, gets a real result back, and feeds it into the model as extra context before the final response — grounded in real data, not a plausible guess. TOOL_INSTRUCTIONS lets you guide HOW and WHEN to use each tool for your specific bot. A genuinely important design decision: which tools should your agent even have access to? A cooking-tips agent benefits from web_search and Wikipedia but has little use for a calculator; a math-tutoring agent absolutely needs the calculator, since even LLMs make basic arithmetic mistakes despite being excellent at language. Choosing the right, minimal tool set keeps your agent focused and predictable.",
  "analogy": "Giving your agent tools is like handing a research assistant a curated toolkit for their exact job — a fact-checker gets a phone and a library card, an estimator gets a calculator and measuring tape. The right, focused toolkit makes them faster and more reliable, not more capable in some vague, unfocused way.",
  "fun_fact": "This ''decide, call, use the result'' pattern is a simplified version of ''function calling'' or ''tool use'' in professional AI systems — one of the most actively developed areas in AI right now, since it lets language models interact with the real world instead of staying purely conversational.",
  "try_it": "If you''re building an agent in FORGE, list which available tools actually make sense for your bot''s specific purpose, and which would just add unnecessary complexity. Write TOOL_INSTRUCTIONS reflecting that focused choice."
}'::jsonb
FROM public.lessons WHERE slug = 'giving-agent-tools';

INSERT INTO public.lesson_content (lesson_id, content)
SELECT id, '{
  "hook": "Ever wondered how an agent ''decides'' which tool to use and when? FORGE has a special mode that makes this reasoning process visible, step by step.",
  "explanation": "When SHOW_REASONING is enabled, instead of jumping straight to a final answer, the model works through a structured pattern called ReAct (Reason + Act): Thought — reasoning about what the question really needs. Action — deciding which tool (if any) to use. Observation — reporting what was actually found. This loop can repeat multiple times for complex questions before arriving at an Answer, synthesizing everything gathered. Why go through all this? Two real reasons. Transparency: a visible reasoning trace lets you catch a flawed step or misused tool before trusting the final answer. And, often more surprising: forcing explicit step-by-step reasoning before committing to an answer often measurably improves accuracy on complex problems — closely related to the ''think step by step'' prompt engineering trick from Module 3. This mirrors how skilled human problem-solvers work through hard problems: reasoning, checking, and reasoning again, not jumping straight to a guess.",
  "analogy": "Thought → Action → Observation is like watching a detective think out loud instead of just announcing ''the culprit is the butler'' with no explanation. Seeing the actual reasoning chain, not just the final verdict, is exactly what makes it trustworthy and checkable.",
  "fun_fact": "The ReAct pattern comes from a real 2022 AI research paper that found combining reasoning traces WITH tool-use actions produced significantly better results than either alone — reasoning without acting can go confidently wrong with no way to check itself, while acting without reasoning can use tools inefficiently.",
  "try_it": "If you have an agent with SHOW_REASONING enabled, ask it a genuinely multi-step question and read through its full trace. Does the reasoning actually make sense at each step, or does it skip logic anywhere?"
}'::jsonb
FROM public.lessons WHERE slug = 'thought-action-observation';

INSERT INTO public.lesson_content (lesson_id, content)
SELECT id, '{
  "hook": "Some tasks can''t be solved in one step, no matter how good the tools or reasoning are. ''Plan a 3-day trip itinerary'' isn''t one lookup — it''s a whole sequence of smaller decisions.",
  "explanation": "Multi-step planning is what happens when an agent breaks a large, complex goal into a sequence of smaller sub-tasks, tackled in order, sometimes adjusting based on what it learns along the way. This builds directly on the Thought → Action → Observation loop — multi-step planning is essentially that same loop repeating multiple times toward one bigger goal. ''Help me plan a birthday party'' isn''t answerable in one shot: figure out guest count and theme, suggest a venue, suggest food, suggest decorations, then pull it together into one coherent plan. Each sub-task might use different tools, and later steps often depend on earlier answers. Good planning requires genuinely tracking state — remembering what''s already been decided, so later steps build on earlier ones instead of contradicting them. This is harder to get right than a single tool call, because errors compound: a wrong assumption in step 1 quietly corrupts everything built on top of it.",
  "analogy": "Multi-step planning is like a general contractor managing a renovation, not a single handyman fixing one thing. The contractor breaks ''renovate the kitchen'' into ordered sub-tasks — demolition, plumbing, electrical, cabinets, paint — because doing them out of order creates real problems. Each step depends on the ones before it going right.",
  "fun_fact": "Multi-step planning is one of the genuinely hardest open challenges in current AI agent research — models are often excellent at any single step in isolation, but reliably chaining many correct steps together remains an active area where even advanced systems still make mistakes humans would easily avoid.",
  "try_it": "Pick a task requiring multiple steps done in the right order. Write out the steps, and notice which later steps genuinely depend on earlier ones being decided first — that dependency chain is exactly what multi-step planning has to track correctly."
}'::jsonb
FROM public.lessons WHERE slug = 'multi-step-planning';

INSERT INTO public.lesson_content (lesson_id, content)
SELECT id, '{
  "hook": "You learned back in Module 3 that a model doesn''t truly ''remember'' between separate conversations — so how do some bots seem to recall your name or something you said days ago? This lesson closes that loop.",
  "explanation": "There are two very different kinds of ''memory'' that get talked about together. Short-term (conversation) memory is simply the conversation history included in the current prompt, within the context window from Module 3 — the model ''remembers'' what you said 5 messages ago because it''s literally still sitting in the prompt text it''s reading right now. Long-term (persistent) memory is different: information deliberately saved OUTSIDE a single conversation, then deliberately retrieved and reinserted into a future, separate conversation''s prompt. In FORGE, REMEMBER_NAME is a simple example: when enabled, a shared name gets noted and referenced later — but the underlying model has no built-in persistent memory of its own; the surrounding application saves that detail and feeds it back into a future prompt. The LLM itself is stateless between calls — zero built-in memory beyond the current prompt''s context window. Any illusion of longer-term memory is the SURROUNDING SYSTEM doing real engineering work, not a hidden capability inside the model.",
  "analogy": "Short-term memory is like reading a conversation transcript someone handed you right before you speak — you can reference everything on the page, but the moment it''s taken away, you have nothing. Long-term memory is more like a personal assistant who takes notes during today''s meeting, files them away, and hands you a relevant summary before tomorrow''s meeting — you didn''t personally remember it; the assistant''s filing system did the work.",
  "fun_fact": "Building genuinely good long-term memory for AI systems is one of the most active areas of current AI product development — deciding WHAT''S worth remembering, HOW to store it, and WHEN to bring it back up (without cluttering future conversations) is a surprisingly hard engineering problem, not a simple toggle.",
  "try_it": "If your FORGE bot has REMEMBER_NAME, test it: tell it your name, then a few messages later ask it to use your name. Notice this ''memory'' is really just conversation history still sitting in the current context window, not a separate memory system."
}'::jsonb
FROM public.lessons WHERE slug = 'agent-memory';

UPDATE public.lessons SET is_published = true WHERE slug IN ('chatbot-vs-agent', 'giving-agent-tools', 'thought-action-observation', 'multi-step-planning', 'agent-memory');

INSERT INTO public.lesson_quiz_questions (lesson_id, order_index, question, options, correct_index, explanation)
SELECT id, q.order_index, q.question, q.options::jsonb, q.correct_index, q.explanation
FROM public.lessons, LATERAL (
  VALUES
    (1, 'What can an agent do that a plain chatbot cannot?', '["Generate any text response at all", "Use real external tools to get current, verifiable information or take real actions", "Have a SYSTEM_MESSAGE", "Respond to user messages"]', 1, 'Tool use is the defining capability separating agents from plain chatbots.'),
    (2, 'What is "hallucination" in the context of AI chatbots?', '["A visual glitch in the chat interface", "The model confidently generating incorrect information based on training patterns rather than verified facts", "A type of temperature setting", "An intentional creative writing feature"]', 1, 'Hallucination refers to confident but incorrect output from learned patterns, not verified truth.'),
    (3, 'What kinds of real actions can a FORGE agent trigger?', '["None, agents cannot do anything chatbots can''t", "Web search, calculation, and Wikipedia lookup", "Physically controlling robots", "Sending emails automatically"]', 1, 'FORGE agents can trigger real web search, calculator, and Wikipedia tools.'),
    (4, 'What is a genuine tradeoff of building an agent compared to a plain chatbot?', '["Agents are always simpler to build", "Agents are more complex to build well and can take slightly longer to respond", "There is no tradeoff whatsoever", "Agents never need a SYSTEM_MESSAGE"]', 1, 'Tool-calling adds complexity and real response-time cost.'),
    (5, 'In the analogy, what does "having a phone in hand to look something up" represent?', '["A plain chatbot''s behavior", "An agent''s ability to use tools instead of relying purely on memory", "A system prompt", "A knowledge base entry"]', 1, 'This mirrors an agent''s real tool-calling capability.'),
    (6, 'Where does the term "agent" in AI originally come from?', '["Invented specifically for chatbots in 2022", "An older concept: anything that perceives its environment and acts to achieve a goal", "A marketing term with no technical meaning", "It refers only to travel agents"]', 1, 'The term predates modern chatbots, describing systems that perceive and act toward goals.'),
    (7, 'What judgment does good agent-building require, per this lesson?', '["Using a tool for every single question, always", "Knowing when a tool call is genuinely needed versus answering directly", "Never using tools under any circumstance", "Randomly deciding whether to use tools"]', 1, 'Good agent design requires judgment about when tool use is actually warranted.')
) AS q(order_index, question, options, correct_index, explanation)
WHERE lessons.slug = 'chatbot-vs-agent';

INSERT INTO public.lesson_quiz_questions (lesson_id, order_index, question, options, correct_index, explanation)
SELECT id, q.order_index, q.question, q.options::jsonb, q.correct_index, q.explanation
FROM public.lessons, LATERAL (
  VALUES
    (1, 'What happens before an agent generates its main response, when tools are available?', '["Nothing different happens compared to a plain chatbot", "A routing step examines whether the message actually requires calling an external tool", "The agent always calls every available tool regardless of need", "The system prompt gets deleted"]', 1, 'A routing step decides whether external tool use is actually needed.'),
    (2, 'What does TOOL_INSTRUCTIONS let you configure?', '["The bot''s name and emoji", "Specific guidance on how and when to use each available tool", "The temperature setting only", "The knowledge base content"]', 1, 'TOOL_INSTRUCTIONS provides bot-specific guidance on tool usage.'),
    (3, 'Why might a math-tutoring bot especially need the calculator tool?', '["Calculators are required by law for AI bots", "LLMs can make basic arithmetic mistakes despite being excellent at language, so the calculator guarantees accuracy", "The calculator tool improves writing style", "It has no particular benefit"]', 1, 'A real calculator tool ensures arithmetic correctness that language models alone can''t guarantee.'),
    (4, 'Why should you choose a focused, minimal tool set rather than enabling everything?', '["More tools always make a bot strictly better", "A focused toolkit keeps the agent''s behavior more predictable and suited to its purpose", "FORGE only allows one tool per bot", "Tools cost money with no other consideration"]', 1, 'A deliberately chosen, minimal toolkit keeps agent behavior focused.'),
    (5, 'In the research assistant analogy, what does a curated, job-specific toolkit represent?', '["Enabling every possible tool regardless of relevance", "Choosing tools specific to the actual job", "Removing all tools entirely", "A knowledge base entry"]', 1, 'A curated toolkit mirrors deliberately choosing relevant tools for a bot''s purpose.'),
    (6, 'What professional term describes the "decide, call, use the result" pattern?', '["Overfitting", "Function calling / tool use", "Dimensionality reduction", "Supervised learning"]', 1, 'This pattern is known professionally as function calling or tool use.'),
    (7, 'Why is function calling/tool use described as an actively developed AI area?', '["It has no real significance", "It''s the key technique letting language models interact with the real world", "It was fully solved decades ago", "It only applies to video games"]', 1, 'Tool use is major because it connects models to real-world data and actions.')
) AS q(order_index, question, options, correct_index, explanation)
WHERE lessons.slug = 'giving-agent-tools';

INSERT INTO public.lesson_quiz_questions (lesson_id, order_index, question, options, correct_index, explanation)
SELECT id, q.order_index, q.question, q.options::jsonb, q.correct_index, q.explanation
FROM public.lessons, LATERAL (
  VALUES
    (1, 'What does the "ReAct" pattern stand for?', '["Reasoning + Action", "Reading + Acting", "Recall + Activation", "Retrieval + Accuracy"]', 0, 'ReAct stands for Reason + Act.'),
    (2, 'What does the "Thought" step involve?', '["Immediately giving the final answer with no explanation", "The model explicitly reasoning about what the question needs", "Calling a tool without any reasoning first", "Ending the conversation"]', 1, 'Thought is the explicit reasoning step before acting.'),
    (3, 'What does the "Observation" step report?', '["The user''s original question restated", "What the model actually found from a tool call it just made", "The bot''s system prompt", "A random guess"]', 1, 'Observation reports the real result from the Action step''s tool call.'),
    (4, 'Why is a visible reasoning trace useful for transparency?', '["It has no practical benefit at all", "It lets you catch flawed steps before trusting the final answer", "It makes responses shorter", "It hides the tool-calling process entirely"]', 1, 'Visible reasoning helps catch errors before the final answer is trusted.'),
    (5, 'Besides transparency, what other benefit does explicit step-by-step reasoning often provide?', '["No other benefit", "It often measurably improves accuracy on complex, multi-step problems", "It always slows the model with no other effect", "It disables tool use"]', 1, 'Explicit reasoning often improves accuracy, similar to prompt engineering techniques.'),
    (6, 'In the detective analogy, what does announcing a verdict with no explanation represent?', '["The full Thought/Action/Observation process", "Skipping the reasoning trace entirely", "An Observation step", "A Thought step"]', 1, 'An unexplained verdict mirrors skipping the transparent reasoning chain.'),
    (7, 'Why is combining reasoning AND acting better than either alone, per the research mentioned?', '["There is no real difference", "Reasoning alone can go confidently wrong; acting alone can use tools inefficiently", "Acting alone is always superior", "Reasoning always requires no tool use"]', 1, 'Combining both addresses the weaknesses of using either approach alone.')
) AS q(order_index, question, options, correct_index, explanation)
WHERE lessons.slug = 'thought-action-observation';

INSERT INTO public.lesson_quiz_questions (lesson_id, order_index, question, options, correct_index, explanation)
SELECT id, q.order_index, q.question, q.options::jsonb, q.correct_index, q.explanation
FROM public.lessons, LATERAL (
  VALUES
    (1, 'What is multi-step planning?', '["Answering every question with a single tool call", "Breaking a large, complex goal into a sequence of smaller sub-tasks, tackled in order", "A setting that disables all tools", "A type of neural network layer"]', 1, 'Multi-step planning decomposes a complex goal into an ordered sequence of sub-tasks.'),
    (2, 'How does multi-step planning relate to Thought → Action → Observation?', '["They are completely unrelated", "Multi-step planning is essentially that same loop repeating toward one bigger goal", "It replaces the need for any reasoning entirely", "They can never be used together"]', 1, 'Multi-step planning builds on ReAct, repeating the loop across sub-tasks.'),
    (3, 'Why does a planning agent need to "track state" well?', '["State tracking is unnecessary", "So later steps build on earlier decisions instead of contradicting them", "To make responses shorter", "To disable tool use after the first step"]', 1, 'Remembering earlier decisions lets later steps build coherently on them.'),
    (4, 'Why can errors in multi-step planning be especially problematic?', '["Errors in one step never affect others", "A wrong assumption early on can quietly corrupt every step built on top of it", "Multi-step planning is immune to errors", "Errors only affect the very first step"]', 1, 'Since later steps depend on earlier ones, mistakes compound through the whole plan.'),
    (5, 'In the contractor analogy, why does order matter (plumbing before cabinets)?', '["Order never actually matters", "Doing steps out of order creates real problems since each depends on prior ones", "Cabinets should always be installed first for no reason", "This analogy is unrelated to dependency"]', 1, 'Planning sub-tasks often have real dependencies requiring correct ordering.'),
    (6, 'Is multi-step planning an easy, fully-solved problem in AI, per this lesson?', '["Yes, solved completely long ago", "No — it remains one of the hardest open challenges in current AI agent research", "It was never actually attempted", "It only matters for trivial tasks"]', 1, 'Multi-step planning remains an active, difficult research area.'),
    (7, 'What example task illustrated multi-step planning in this lesson?', '["Answering a single trivia question", "Planning a birthday party, broken into guest count, venue, food, decorations, and a final plan", "Calculating a simple math problem", "Translating one sentence"]', 1, 'The birthday party example illustrates breaking a goal into ordered sub-tasks.')
) AS q(order_index, question, options, correct_index, explanation)
WHERE lessons.slug = 'multi-step-planning';

INSERT INTO public.lesson_quiz_questions (lesson_id, order_index, question, options, correct_index, explanation)
SELECT id, q.order_index, q.question, q.options::jsonb, q.correct_index, q.explanation
FROM public.lessons, LATERAL (
  VALUES
    (1, 'What is "short-term (conversation) memory" in an LLM-based chatbot?', '["A separate database the model consults", "Simply the conversation history included in the current prompt''s context window", "A hidden internal memory chip", "Information saved permanently inside the model''s parameters"]', 1, 'Short-term memory is recent conversation history still present in the current prompt.'),
    (2, 'What is "long-term (persistent) memory"?', '["Exactly the same as short-term memory", "Information deliberately saved outside a single conversation and reinserted into future ones", "A feature that doesn''t exist in any AI system", "Something the model does entirely on its own"]', 1, 'Long-term memory requires deliberate external storage and retrieval.'),
    (3, 'Is the underlying LLM itself stateful or stateless between separate calls?', '["Stateful — it remembers everything automatically", "Stateless — zero built-in memory beyond the current prompt''s context window", "It depends randomly each time", "Only agents are stateless; chatbots are stateful"]', 1, 'The LLM itself is stateless between calls.'),
    (4, 'In FORGE, what is actually doing the "remembering" when REMEMBER_NAME is enabled?', '["The model itself has built-in persistent memory", "The surrounding application, which saves the detail and feeds it back into a future prompt", "Nothing is actually being remembered", "The user''s browser, unrelated to the bot"]', 1, 'The surrounding application does the real work of saving and reinserting information.'),
    (5, 'In the transcript analogy, what happens when "the page is taken away"?', '["Nothing changes, memory persists", "You have nothing — mirroring how short-term memory disappears outside the context window", "This represents long-term memory specifically", "The conversation restarts with full memory intact"]', 1, 'Losing the transcript mirrors losing short-term memory outside the context window.'),
    (6, 'In the personal assistant analogy, what does filing notes for tomorrow represent?', '["Short-term memory", "Long-term (persistent) memory implemented by an external system", "The model''s temperature setting", "A hallucination"]', 1, 'An assistant''s filing/retrieval system mirrors externally implemented long-term memory.'),
    (7, 'Why is building good long-term memory described as "a surprisingly hard engineering problem"?', '["It''s trivial and requires no design decisions", "Deciding what''s worth remembering, how to store it, and when to retrieve it is genuinely difficult", "Long-term memory has been perfectly solved everywhere", "It only requires a simple on/off toggle"]', 1, 'Effective long-term memory requires real design decisions about relevance, storage, and retrieval.')
) AS q(order_index, question, options, correct_index, explanation)
WHERE lessons.slug = 'agent-memory';
