-- Module 7 (Responsible & Ethical AI) content enrichment: adds visual diagrams,
-- in-lesson practice checks, and worked code examples (Bias in AI / Privacy,
-- Safety & Guardrails). Additive only (jsonb ||), existing hook/explanation/
-- analogy/fun_fact/try_it fields are untouched.
--
-- Matched by module_number + title, NOT order_index -- other, separately-run
-- migrations renumber order_index as new lessons get inserted elsewhere in the
-- curriculum, so an order_index-based match here would silently target the
-- wrong lessons depending on what's already been applied when this runs.
--
-- 'Your Path Forward' deliberately stays internal-only for its next-steps
-- (more FORGE/Me AI projects, Python Challenges, hackathons, portfolio,
-- teaching others) rather than pointing students to external courses.

UPDATE public.lesson_content lc
SET content = lc.content || '{"code":"# A simplified fairness check: does accuracy differ across groups?\nresults = [\n    {\"group\": \"A\", \"predicted_correct\": True},\n    {\"group\": \"A\", \"predicted_correct\": True},\n    {\"group\": \"A\", \"predicted_correct\": False},\n    {\"group\": \"B\", \"predicted_correct\": False},\n    {\"group\": \"B\", \"predicted_correct\": False},\n    {\"group\": \"B\", \"predicted_correct\": True},\n]\n\ndef accuracy_by_group(results):\n    groups = {}\n    for r in results:\n        g = r[\"group\"]\n        groups.setdefault(g, []).append(r[\"predicted_correct\"])\n    return {g: sum(vals) / len(vals) for g, vals in groups.items()}\n\nacc = accuracy_by_group(results)\nfor group, score in acc.items():\n    print(f\"Group {group}: {score:.0%} accuracy\")\n\ngap = max(acc.values()) - min(acc.values())\nprint(f\"Accuracy gap between groups: {gap:.0%}\")","visual":{"caption":"Why \"it works\" is never enough — you have to ask \"works for whom?\"","steps":[{"emoji":"📊","label":"Overall Accuracy Looks Fine","caption":"A single headline number can hide a lot."},{"emoji":"✂️","label":"Split By Group","caption":"Check performance separately for each group that matters."},{"emoji":"⚠️","label":"Real Gap Revealed","caption":"One group is quietly served worse than another."},{"emoji":"🔍","label":"Investigate","caption":"Trace it back — usually to the training data."},{"emoji":"🛠️","label":"Fix","caption":"Collect better data, or add group-aware evaluation permanently."}]},"practice":{"prompt":"In the code above, why is looking only at OVERALL accuracy across both groups misleading?","options":["It hides a real 33-percentage-point gap between how well the model serves Group A vs. Group B","Overall accuracy is always more accurate than per-group accuracy","There is no way to check accuracy by group in real systems","The gap shown is not a real problem, just a coincidence"],"correct_index":0,"feedback":"Exactly the pattern from the real face-analysis audit: a fine-looking overall number was hiding a massive gap between groups. Checking by group is the only way to catch it."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.module_number = 7 AND l.title = 'Bias in AI';

UPDATE public.lesson_content lc
SET content = lc.content || '{"code":"import re\n\ndef redact_pii(text):\n    # simplified patterns -- real systems use far more robust detection\n    text = re.sub(r\"\\b\\d{10}\\b\", \"[PHONE REDACTED]\", text)\n    text = re.sub(r\"[\\w.+-]+@[\\w-]+\\.[\\w.-]+\", \"[EMAIL REDACTED]\", text)\n    return text\n\nuser_message = \"Hi, my number is 0244123456 and my email is ama@example.com\"\nprint(redact_pii(user_message))\n\n# A guardrail: block a request before it ever reaches the model\ndef check_guardrail(message):\n    blocked_topics = [\"how to build a weapon\", \"self-harm methods\"]\n    return any(topic in message.lower() for topic in blocked_topics)\n\nprint(check_guardrail(\"Tell me a joke\"))                 # False -> allowed\nprint(check_guardrail(\"how to build a weapon at home\"))  # True -> blocked","visual":{"caption":"Guardrails sit on BOTH sides of the model, not just one","steps":[{"emoji":"📥","label":"Input Arrives","caption":"A message comes in from a real user."},{"emoji":"🛡️","label":"Input Guardrail","caption":"Check for PII, blocked topics, injection attempts."},{"emoji":"🧠","label":"Model Runs","caption":"Only cleared, safe input reaches the model."},{"emoji":"🛡️","label":"Output Guardrail","caption":"Check what the model wants to say BEFORE it''s shown."},{"emoji":"📤","label":"Safe Response","caption":"What the user actually sees."}]},"practice":{"prompt":"A team only checks user INPUT for problems, never the model''s OUTPUT. What real risk does this miss?","options":["The model itself could still generate something harmful, biased, or leak private data in its response — even from a totally safe input","There is no risk — checking input is always sufficient","Output can never contain anything the input did not already contain","Guardrails only ever need to run once per conversation"],"correct_index":0,"feedback":"A safe question can still get an unsafe answer — the model can hallucinate, leak training data patterns, or drift off-topic. Real systems guardrail both directions."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.module_number = 7 AND l.title = 'Privacy, Safety & Guardrails';

UPDATE public.lesson_content lc
SET content = lc.content || '{"visual":{"caption":"AI''s real effects are more mixed than most headlines suggest","steps":[{"emoji":"💼","label":"Jobs: Displaced AND Created","caption":"Some tasks disappear, new roles (like AI Ethicist) appear — rarely a clean swap."},{"emoji":"🎭","label":"Misinformation & Deepfakes","caption":"Convincing fake content at a speed and scale humans cannot fact-check manually."},{"emoji":"💰","label":"Economic Concentration","caption":"Training the largest models takes resources only a few organizations have."},{"emoji":"🌍","label":"Access & Digital Divide","caption":"Reliable internet and devices are still not evenly distributed globally."},{"emoji":"🎨","label":"New Creative Possibilities","caption":"Tools that let more people build, design, and create than ever before."}]},"practice":{"prompt":"\"AI will replace most jobs\" is a common headline. What is the more accurate, nuanced version?","options":["AI tends to automate specific TASKS within a job, not entire jobs outright — most roles change rather than vanish","AI has replaced every job that existed before 2020","AI has had literally zero effect on any job anywhere","Only creative jobs are affected by AI, no others"],"correct_index":0,"feedback":"Most real-world evidence points to task-level automation, not wholesale job elimination — a task getting faster with AI usually means the job shifts, not disappears."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.module_number = 7 AND l.title = 'AI''s Impact on Society';

UPDATE public.lesson_content lc
SET content = lc.content || '{"visual":{"caption":"This academy is your foundation, not your ceiling","steps":[{"emoji":"🏗️","label":"Keep Building","caption":"Build 2-3 more real FORGE/Me AI projects — depth beats re-reading notes."},{"emoji":"🐍","label":"Level Up Your Python","caption":"Tackle the Python Challenges track for real, hands-on coding practice."},{"emoji":"🏆","label":"Enter a Hackathon","caption":"Compete in FORGE hackathons and get real feedback from judges."},{"emoji":"📁","label":"Build a Portfolio","caption":"Publish your best projects so people see real, working proof — not just a certificate."},{"emoji":"🎓","label":"Teach Someone Else","caption":"Explaining a concept to someone else is one of the fastest ways to truly cement it."}]},"practice":{"prompt":"You''ve finished the AI & ML Academy. What''s the most effective next step?","options":["Build another real project and enter a hackathon to get real feedback on it","Stop learning — you now know everything there is to know about AI","Only re-read your notes passively, with no new building","Wait for someone else to walk you through every next step"],"correct_index":0,"feedback":"The pattern that actually works, here and everywhere: build something real, then get it in front of real feedback — exactly how this whole academy was structured."}}'::jsonb
FROM public.lessons l
WHERE l.id = lc.lesson_id AND l.module_number = 7 AND l.title = 'Your Path Forward';

